### ISSUE TITLE
Download not started 

### ISSUE THREAD

**Issue by SupportAnalytic** [heliomarpm/udemy-downloader-gui#115]
19/04/2023 10:07:36 - uncaughtException: TypeError: axios(...).done is not a function
    at file:///C:/Users/Deuter%C3%B4nomio%2028/AppData/Local/Programs/udeler/resources/app.asar/assets/js/app.js:916:20
    at sentryWrapped (C:\Users\Deuterônomio 28\AppData\Local\Programs\udeler\resources\app.asar\node_modules\@sentry\browser\cjs\helpers.js:92:17)
19/04/2023 10:07:35 - uncaughtException: TypeError: axios(...).done is not a function
    at file:///C:/Users/Deuter%C3%B4nomio%2028/AppData/Local/Programs/udeler/resources/app.asar/assets/js/app.js:916:20
    at sentryWrapped (C:\Users\Deuterônomio 28\AppData\Local\Programs\udeler\resources\app.asar\node_modules\@sentry\browser\cjs\helpers.js:92:17)
19/04/2023 10:07:34 - uncaughtException: TypeError: axios(...).done is not a function
    at file:///C:/Users/Deuter%C3%B4nomio%2028/AppData/Local/Programs/udeler/resources/app.asar/assets/js/app.js:916:20
    at sentryWrapped (C:\Users\Deuterônomio 28\AppData\Local\Programs\udeler\resources\app.asar\node_modules\@sentry\browser\cjs\helpers.js:92:17)
19/04/2023 10:07:33 - uncaughtException: TypeError: axios(...).done is not a function
    at file:///C:/Users/Deuter%C3%B4nomio%2028/AppData/Local/Programs/udeler/resources/app.asar/assets/js/app.js:916:20
    at sentryWrapped (C:\Users\Deuterônomio 28\AppData\Local\Programs\udeler\resources\app.asar\node_modules\@sentry\browser\cjs\helpers.js:92:17)
19/04/2023 10:07:32 - uncaughtException: TypeError: axios(...).done is not a function
    at file:///C:/Users/Deuter%C3%B4nomio%2028/AppData/Local/Programs/udeler/resources/app.asar/assets/js/app.js:916:20
    at sentryWrapped (C:\Users\Deuterônomio 28\AppData\Local\Programs\udeler\resources\app.asar\node_modules\@sentry\browser\cjs\helpers.js:92:17)
19/04/2023 10:07:31 - uncaughtException: TypeError: axios(...).done is not a function
    at file:///C:/Users/Deuter%C3%B4nomio%2028/AppData/Local/Programs/udeler/resources/app.asar/assets/js/app.js:916:20
    at sentryWrapped (C:\Users\Deuterônomio 28\AppData\Local\Programs\udeler\resources\app.asar\node_modules\@sentry\browser\cjs\helpers.js:92:17)

[udeler_logger.txt](https://github.com/heliomarpm/udemy-downloader-gui/files/11273413/udeler_logger.txt)
![Capturar](https://user-images.githubusercontent.com/88642011/233087194-a0a5d557-42af-41ca-a8ba-dfbf567b5cf2.PNG)
![Screenshot_5](https://user-images.githubusercontent.com/88642011/233092500-52ed7ece-69e4-444d-94de-52adcde29511.png)
![Capturar](https://user-images.githubusercontent.com/88642011/233092505-0d090a64-0ea9-4bec-b825-6dd89f32b2e4.PNG)
![Screenshot_1](https://user-images.githubusercontent.com/88642011/233092508-718913cd-e7d1-4f6f-923d-43690b63ea64.png)
![Screenshot_3](https://user-images.githubusercontent.com/88642011/233092515-c23eb77d-11f3-4ed9-a7a9-fe8f747955ed.png)
![Screenshot_4](https://user-images.githubusercontent.com/88642011/233092517-bc076178-5419-4f82-abad-242c74342c84.png)

**Comment by heliomarpm** [comment]
Já tem uma correção prevista para esse domingo 23/04

**Comment by heliomarpm** [comment]
Check the latest version
