### ISSUE TITLE
npm start didn't work at all for me. Seems to be electron version issue

### ISSUE THREAD

**Issue by Blank000** [heliomarpm/udemy-downloader-gui#83]
### Udeler | Udemy Course Downloader

1.11.4

### Running as Business Account

- [ ] Yes

### Steps to reproduce

Running `npm install`

### ✔️ Expected Behavior

For the npm install to work properly.

### ❌ Actual Behavior

It failed with below error - 

```
npm WARN deprecated dmg-license@1.0.11: Disk image license agreements are deprecated by Apple and will probably be removed in a future macOS release. Discussion at: https://github.com/argv-minus-one/dmg-license/issues/11
npm ERR! code 1
npm ERR! path /Users/muffycoder/Downloads/udemy-downloader-gui-1.11.4/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! node:internal/process/promises:289
npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
npm ERR!             ^
npm ERR!
npm ERR! GotError [HTTPError]: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v8.2.4/electron-v8.2.4-darwin-arm64.zip
npm ERR!     at EventEmitter.<anonymous> (/Users/muffycoder/Downloads/udemy-downloader-gui-1.11.4/node_modules/got/source/as-stream.js:35:24)
npm ERR!     at EventEmitter.emit (node:events:513:28)
npm ERR!     at module.exports (/Users/muffycoder/Downloads/udemy-downloader-gui-1.11.4/node_modules/got/source/get-response.js:22:10)
npm ERR!     at ClientRequest.handleResponse (/Users/muffycoder/Downloads/udemy-downloader-gui-1.11.4/node_modules/got/source/request-as-event-emitter.js:155:5)
npm ERR!     at Object.onceWrapper (node:events:628:26)
npm ERR!     at ClientRequest.emit (node:events:525:35)
npm ERR!     at origin.emit (/Users/muffycoder/Downloads/udemy-downloader-gui-1.11.4/node_modules/@szmarczak/http-timer/source/index.js:37:11)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:688:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:530:22) {
npm ERR!   host: 'github.com',
npm ERR!   hostname: 'github.com',
npm ERR!   method: 'GET',
npm ERR!   path: '/electron/electron/releases/download/v8.2.4/electron-v8.2.4-darwin-arm64.zip',
npm ERR!   socketPath: undefined,
npm ERR!   protocol: 'https:',
npm ERR!   url: 'https://github.com/electron/electron/releases/download/v8.2.4/electron-v8.2.4-darwin-arm64.zip',
npm ERR!   gotOptions: {
npm ERR!     path: '/electron/electron/releases/download/v8.2.4/electron-v8.2.4-darwin-arm64.zip',
npm ERR!     protocol: 'https:',
npm ERR!     slashes: true,
npm ERR!     auth: null,
npm ERR!     host: 'github.com',
npm ERR!     port: null,
npm ERR!     hostname: 'github.com',
npm ERR!     hash: null,
npm ERR!     search: null,
npm ERR!     query: null,
npm ERR!     pathname: '/electron/electron/releases/download/v8.2.4/electron-v8.2.4-darwin-arm64.zip',
npm ERR!     href: 'https://github.com/electron/electron/releases/download/v8.2.4/electron-v8.2.4-darwin-arm64.zip',
npm ERR!     retry: {
npm ERR!       retries: [Function (anonymous)],
npm ERR!       methods: Set(6) { 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' },
npm ERR!       statusCodes: Set(7) { 408, 413, 429, 500, 502, 503, 504 },
npm ERR!       errorCodes: Set(8) {
npm ERR!         'ETIMEDOUT',
npm ERR!         'ECONNRESET',
npm ERR!         'EADDRINUSE',
npm ERR!         'ECONNREFUSED',
npm ERR!         'EPIPE',
npm ERR!         'ENOTFOUND',
npm ERR!         'ENETUNREACH',
npm ERR!         'EAI_AGAIN'
npm ERR!       }
npm ERR!     },
npm ERR!     headers: {
npm ERR!       'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
npm ERR!       'accept-encoding': 'gzip, deflate'
npm ERR!     },
npm ERR!     hooks: {
npm ERR!       beforeRequest: [],
npm ERR!       beforeRedirect: [],
npm ERR!       beforeRetry: [],
npm ERR!       afterResponse: [],
npm ERR!       beforeError: [],
npm ERR!       init: []
npm ERR!     },
npm ERR!     decompress: true,
npm ERR!     throwHttpErrors: true,
npm ERR!     followRedirect: true,
npm ERR!     stream: true,
npm ERR!     form: false,
npm ERR!     json: false,
npm ERR!     cache: false,
npm ERR!     useElectronNet: false,
npm ERR!     method: 'GET'
npm ERR!   },
npm ERR!   statusCode: 404,
npm ERR!   statusMessage: 'Not Found',
npm ERR!   headers: {
npm ERR!     server: 'GitHub.com',
npm ERR!     date: 'Sun, 11 Dec 2022 04:03:17 GMT',
npm ERR!     'content-type': 'text/plain; charset=utf-8',
npm ERR!     vary: 'X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With',
npm ERR!     'cache-control': 'no-cache',
npm ERR!     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
npm ERR!     'x-frame-options': 'deny',
npm ERR!     'x-content-type-options': 'nosniff',
npm ERR!     'x-xss-protection': '0',
npm ERR!     'referrer-policy': 'no-referrer-when-downgrade',
npm ERR!     'content-security-policy': "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
npm ERR!     'content-encoding': 'gzip',
npm ERR!     'content-length': '29',
npm ERR!     'x-github-request-id': 'E172:1CCB:5E954:468F7E:63955685'
npm ERR!   },
npm ERR!   body: undefined
npm ERR! }
npm ERR!
npm ERR! Node.js v19.2.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/muffycoder/.npm/_logs/2022-12-11T04_02_48_779Z-debug-0.log
```

**Comment by heliomarpm** [comment]
Hi @Blank000, please, check the node and npm version.

I thought it might be a problem with some deprecated package, but I just cloned it and everything installed without a problem.

Look.
![image](https://user-images.githubusercontent.com/13087389/207053421-56fe5a29-c8fd-4705-84d3-eaca15bb2626.png)

**Comment by Blank000** [comment]
Did you do anything prehand, like installing something beforehand only ? Something must be missing here which it's not able to find it now.

I actually tried abov steps, even chaged the node and npm version but still getting below error - 



```
muffycoder@Prataps-MacBook-Pro udemy-downloader-gui % npm i 
npm WARN skipping integrity check for git dependency ssh://git@github.com/riazXrazor/vtt-to-srt.git 
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated dmg-license@1.0.11: Disk image license agreements are deprecated by Apple and will probably be removed in a future macOS release. Discussion at: https://github.com/argv-minus-one/dmg-license/issues/11
npm ERR! code 1
npm ERR! path /Users/muffycoder/Downloads/udemy-downloader-gui/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! node:internal/process/promises:289
npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
npm ERR!             ^
npm ERR! 
npm ERR! GotError [HTTPError]: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v8.2.4/electron-v8.2.4-darwin-arm64.zip
npm ERR!     at EventEmitter.<anonymous> (/Users/muffycoder/Downloads/udemy-downloader-gui/node_modules/got/source/as-stream.js:35:24)
npm ERR!     at EventEmitter.emit (node:events:513:28)
npm ERR!     at module.exports (/Users/muffycoder/Downloads/udemy-downloader-gui/node_modules/got/source/get-response.js:22:10)
npm ERR!     at ClientRequest.handleResponse (/Users/muffycoder/Downloads/udemy-downloader-gui/node_modules/got/source/request-as-event-emitter.js:155:5)
npm ERR!     at Object.onceWrapper (node:events:628:26)
npm ERR!     at ClientRequest.emit (node:events:525:35)
npm ERR!     at origin.emit (/Users/muffycoder/Downloads/udemy-downloader-gui/node_modules/@szmarczak/http-timer/source/index.js:37:11)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:688:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:530:22) {
npm ERR!   host: 'github.com',
npm ERR!   hostname: 'github.com',
npm ERR!   method: 'GET',
npm ERR!   path: '/electron/electron/releases/download/v8.2.4/electron-v8.2.4-darwin-arm64.zip',
npm ERR!   socketPath: undefined,
npm ERR!   protocol: 'https:',
npm ERR!   url: 'https://github.com/electron/electron/releases/download/v8.2.4/electron-v8.2.4-darwin-arm64.zip',
npm ERR!   gotOptions: {
npm ERR!     path: '/electron/electron/releases/download/v8.2.4/electron-v8.2.4-darwin-arm64.zip',
npm ERR!     protocol: 'https:',
npm ERR!     slashes: true,
npm ERR!     auth: null,
npm ERR!     host: 'github.com',
npm ERR!     port: null,
npm ERR!     hostname: 'github.com',
npm ERR!     hash: null,
npm ERR!     search: null,
npm ERR!     query: null,
npm ERR!     pathname: '/electron/electron/releases/download/v8.2.4/electron-v8.2.4-darwin-arm64.zip',
npm ERR!     href: 'https://github.com/electron/electron/releases/download/v8.2.4/electron-v8.2.4-darwin-arm64.zip',
npm ERR!     retry: {
npm ERR!       retries: [Function (anonymous)],
npm ERR!       methods: Set(6) { 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' },
npm ERR!       statusCodes: Set(7) { 408, 413, 429, 500, 502, 503, 504 },
npm ERR!       errorCodes: Set(8) {
npm ERR!         'ETIMEDOUT',
npm ERR!         'ECONNRESET',
npm ERR!         'EADDRINUSE',
npm ERR!         'ECONNREFUSED',
npm ERR!         'EPIPE',
npm ERR!         'ENOTFOUND',
npm ERR!         'ENETUNREACH',
npm ERR!         'EAI_AGAIN'
npm ERR!       }
npm ERR!     },
npm ERR!     headers: {
npm ERR!       'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
npm ERR!       'accept-encoding': 'gzip, deflate'
npm ERR!     },
npm ERR!     hooks: {
npm ERR!       beforeRequest: [],
npm ERR!       beforeRedirect: [],
npm ERR!       beforeRetry: [],
npm ERR!       afterResponse: [],
npm ERR!       beforeError: [],
npm ERR!       init: []
npm ERR!     },
npm ERR!     decompress: true,
npm ERR!     throwHttpErrors: true,
npm ERR!     followRedirect: true,
npm ERR!     stream: true,
npm ERR!     form: false,
npm ERR!     json: false,
npm ERR!     cache: false,
npm ERR!     useElectronNet: false,
npm ERR!     method: 'GET'
npm ERR!   },
npm ERR!   statusCode: 404,
npm ERR!   statusMessage: 'Not Found',
npm ERR!   headers: {
npm ERR!     server: 'GitHub.com',
npm ERR!     date: 'Mon, 12 Dec 2022 14:25:42 GMT',
npm ERR!     'content-type': 'text/plain; charset=utf-8',
npm ERR!     vary: 'X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With',
npm ERR!     'cache-control': 'no-cache',
npm ERR!     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
npm ERR!     'x-frame-options': 'deny',
npm ERR!     'x-content-type-options': 'nosniff',
npm ERR!     'x-xss-protection': '0',
npm ERR!     'referrer-policy': 'no-referrer-when-downgrade',
npm ERR!     'content-security-policy': "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
npm ERR!     'content-encoding': 'gzip',
npm ERR!     'content-length': '29',
npm ERR!     'x-github-request-id': 'CDE4:30F5:3A7B7:5B248:639739E6'
npm ERR!   },
npm ERR!   body: undefined
npm ERR! }
npm ERR! 
npm ERR! Node.js v19.2.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/muffycoder/.npm/_logs/2022-12-12T14_25_36_803Z-debug-0.log
```

**Comment by heliomarpm** [comment]
Hi @Blank000 
Could you try again with the latest version?
some packages updated

**Comment by heliomarpm** [comment]
Reported solution
https://github.com/heliomarpm/udemy-downloader-gui/issues/95#issuecomment-1438704646

**Comment by IgorShch** [comment]
Not sure if it's related

I get the following when I run npm start 

Error: ENOENT: no such file or directory, open '/Users/igorshchukin/Documents/Dev/udemy-downloader-gui/.env'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:468:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at Object.<anonymous> (/Users/igorshchukin/Documents/Dev/udemy-downloader-gui/environments.js:3:20)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)

I use MacOs Monterey 12.4 Apple M1

**Comment by heliomarpm** [comment]
> Not sure if it's related
> 
> I get the following when I run npm start
> 
> Error: ENOENT: no such file or directory, open '/Users/igorshchukin/Documents/Dev/udemy-downloader-gui/.env' at Object.openSync (node:fs:600:3) at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822) at Object.readFileSync (node:fs:468:35) at t.readFileSync (node:electron/js2c/asar_bundle:2:9165) at Object. (/Users/igorshchukin/Documents/Dev/udemy-downloader-gui/environments.js:3:20) at Module._compile (node:internal/modules/cjs/loader:1174:14) at Module._extensions..js (node:internal/modules/cjs/loader:1229:10) at Module.load (node:internal/modules/cjs/loader:1044:32) at Module._load (node:internal/modules/cjs/loader:885:12) at f._load (node:electron/js2c/asar_bundle:2:13330)
> 
> I use MacOs Monterey 12.4 Apple M1

rename file .env.example to .env
